version: '3.8'
services:
  homeassistant:
    image: homeassistant/home-assistant:latest 
    container_name: home assistant
    environment:
      - TZ=Europe/Paris
    ports:
      - 8123:8123
    volumes:
      - /conteneurs/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
